Repository yashlad27/PDPAssignment5, pull requests merged in 2025-03, with the labels that each got.

#1 Enhancement branch 1
  .idea/misc.xml
  src/controller/command/CreateEventCommand.java
  src/model/calendar/Calendar.java
  src/model/event/RecurringEvent.java
  src/model/exceptions/ConflictingEventException.java
  src/model/exceptions/EventNotFoundException.java
  src/model/exceptions/InvalidEventException.java
  src/view/ConsoleView.java
  src/view/ICalendarView.java
Labels: enhancement

#4 checked_exception_feature_branch
  pom.xml
  src/view/ConsoleView.java
  src/view/ICalendarView.java
Labels: enhancement

#5 checked_exception_feature_branch
  pom.xml
  src/controller/command/EditEventCommand.java
  src/controller/command/ICommand.java
  src/controller/parser/CommandParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/ICalendar.java
  src/test/CSVExporterTest.java
  src/test/CalendarControllerTest.java
  src/test/CalendarTest.java
  src/test/CommandFactoryTest.java
  src/test/CommandParserTest.java
  src/test/ConsoleViewTest.java
  src/test/CreateEventCommandTest.java
  src/test/DateTimeUtilTest.java
  src/test/EditEventCommandTest.java
  src/test/EventTest.java
  src/test/ExitCommandTest.java
  src/test/ExportCalendarCommandTest.java
  src/test/PrintEventsCommandTest.java
  src/test/RecurringEventTest.java
  src/test/ShowStatusCommandTest.java
Labels: enhancement

#6 time zone handler branch
  src/utilities/TimeZoneHandler.java
Labels: A5_Feature

#7 Yash branch
  src/model/calendar/CalendarManager.java
  src/model/exceptions/CalendarNotFoundException.java
  src/model/exceptions/DuplicateCalendarException.java
  src/model/exceptions/InvalidTimezoneException.java
  src/utilities/TimeZoneHandler.java
Labels: A5_Feature

#8 Feature calendar manager class
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
Labels: A5_Feature

#9 feature_functional_interface_branch
  src/model/calendar/CalendarOperation.java
  src/model/calendar/EventFilter.java
  src/model/event/EventAction.java
  src/model/event/EventCreationStrategy.java
  src/utilities/EventPropertyUpdater.java
Labels: A5_Feature

#10 New Functional Interface in controller and model
  src/controller/command/CommandExecutor.java
  src/model/calendar/CalendarOperation.java
  src/model/calendar/EventFilter.java
Labels: enhancement, A5_Feature

#12 Property updation code added and Calendar CRUD
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CalendarCommandHandler.java
  src/controller/command/CommandFactory.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
Labels: A5_Feature

#14 Calendar Application Update
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CommandFactory.java
  src/controller/command/CopyEventCommand.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/event/EventCreationStrategy.java
  src/utilities/TimeZoneHandler.java
Labels: enhancement, A5_Feature

#15 Implement Multi-Calendar Management and Enhanced Command Handling
  src/controller/command/CommandFactory.java
  src/controller/command/CreateEventCommand.java
  src/model/calendar/Calendar.java
  src/model/event/EventAction.java
  src/model/event/RecurringEvent.java
  src/utilities/TimezoneConverter.java
Labels: enhancement, A5_Feature

#16 Adapter Design pattern
  src/controller/command/CommandAdapter.java
  src/controller/parser/CommandParser.java
Labels: A5_Feature, donedev

#17 Copy command concrete classes and new interface
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/copy/CopyCommand.java
  src/controller/command/copy/CopyEventCommand.java
  src/controller/command/copy/CopyEventsBetweenDatesCommand.java
  src/controller/command/copy/CopyEventsOnDateCommand.java
  src/controller/parser/CommandParser.java
Labels: A5_Feature, indev

#19 edit event new implementation and copy command implementation added
  src/controller/CalendarController.java
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CommandFactory.java
  src/controller/command/copy/CopyEventCommand.java
  src/controller/parser/CommandParser.java
  src/resources/calcmd.txt
Labels: enhancement, wip, indev

#20 Fix for copy error and edit calendar event error
  src/controller/CalendarController.java
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CopyEventCommand.java
  src/controller/command/copy/CopyEventCommand.java
Labels: enhancement, A5_Feature, wip, indev

#21 Feature timezone fix for mulcal
  src/controller/command/CopyEventCommand.java
  src/controller/command/copy/CopyEventCommand.java
  src/controller/command/copy/CopyEventsBetweenDatesCommand.java
  src/controller/command/copy/CopyEventsOnDateCommand.java
  src/model/calendar/Calendar.java
  src/utilities/TimeZoneHandler.java
  src/utilities/TimezoneConverter.java
Labels: enhancement, A5_Feature, indev

#23 Feature solids fix
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/ICommandFactory.java
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CommandFactory.java
  src/controller/command/CopyEventCommand.java
  src/controller/command/CreateEventCommand.java
  src/controller/parser/CommandParser.java
  src/controller/parser/CommandPatternParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/calendar/CalendarRegistry.java
  src/model/event/RecurringEvent.java
  src/model/factory/CalendarFactory.java
Labels: bug, A5_Feature, indev

#25 Feature strategy pattern part2
  src/controller/CalendarController.java
  src/controller/command/CopyEventCommand.java
  src/controller/command/copy/CopyStrategy.java
  src/controller/command/copy/CopyStrategyFactory.java
  src/controller/command/copy/DayEventsCopyStrategy.java
  src/controller/command/copy/RangeEventsCopyStrategy.java
  src/controller/command/copy/SingleEventCopyStrategy.java
  src/resources/headlessCmd.txt
Labels: testing, donedev, newMod

#24 Key changes in this implementation:
  src/controller/CalendarController.java
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CopyEventCommand.java
  src/controller/command/copy/CopyCommand.java
  src/controller/command/copy/CopyEventCommand.java
  src/controller/command/copy/CopyEventsBetweenDatesCommand.java
  src/controller/command/copy/CopyEventsOnDateCommand.java
  src/controller/command/copy/CopyStrategy.java
  src/controller/command/copy/CopyStrategyFactory.java
  src/controller/command/copy/DayEventsCopyStrategy.java
  src/controller/command/copy/RangeEventsCopyStrategy.java
  src/controller/command/copy/SingleEventCopyStrategy.java
  src/resources/cmd10.txt
  src/resources/headlessCmd.txt
Labels: bug

#26 Edit event patch fix
  src/controller/parser/CommandParser.java
Labels: enhancement, A5_Feature, donedev

#27 Assignment 5 - Implementation
  .idea/misc.xml
  pom.xml
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/ICommandFactory.java
  src/controller/command/CalendarCommandFactory.java
  src/controller/command/CalendarCommandHandler.java
  src/controller/command/CommandAdapter.java
  src/controller/command/CommandExecutor.java
  src/controller/command/CommandFactory.java
  src/controller/command/CopyEventCommand.java
  src/controller/command/CreateEventCommand.java
  src/controller/command/EditEventCommand.java
  src/controller/command/ICommand.java
  src/controller/command/copy/CopyStrategy.java
  src/controller/command/copy/CopyStrategyFactory.java
  src/controller/command/copy/DayEventsCopyStrategy.java
  src/controller/command/copy/RangeEventsCopyStrategy.java
  src/controller/command/copy/SingleEventCopyStrategy.java
  src/controller/parser/CommandParser.java
  src/controller/parser/CommandPatternParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/calendar/CalendarOperation.java
  src/model/calendar/CalendarRegistry.java
  src/model/calendar/EventFilter.java
  src/model/calendar/ICalendar.java
  src/model/event/EventAction.java
  src/model/event/EventCreationStrategy.java
  src/model/event/RecurringEvent.java
  src/model/exceptions/CalendarNotFoundException.java
  src/model/exceptions/ConflictingEventException.java
  src/model/exceptions/DuplicateCalendarException.java
  src/model/exceptions/EventNotFoundException.java
  src/model/exceptions/InvalidEventException.java
  src/model/exceptions/InvalidTimezoneException.java
  src/model/factory/CalendarFactory.java
  src/resources/calcmd.txt
  src/resources/cmd10.txt
  src/resources/headlessCmd.txt
  src/test/CSVExporterTest.java
  src/test/CalendarControllerTest.java
  src/test/CalendarTest.java
  src/test/CommandFactoryTest.java
  src/test/CommandParserTest.java
  src/test/ConsoleViewTest.java
  src/test/CreateEventCommandTest.java
  src/test/DateTimeUtilTest.java
  src/test/EditEventCommandTest.java
  src/test/EventTest.java
  src/test/ExitCommandTest.java
  src/test/ExportCalendarCommandTest.java
  src/test/PrintEventsCommandTest.java
  src/test/RecurringEventTest.java
  src/test/ShowStatusCommandTest.java
  src/utilities/EventPropertyUpdater.java
  src/utilities/TimeZoneHandler.java
  src/utilities/TimezoneConverter.java
Labels: A5_Feature, donedev, newMod

#28 Feature create strategy pattern
  src/controller/command/CommandFactory.java
  src/controller/command/create/AbstractEventCreator.java
  src/controller/command/create/AllDayEventCreator.java
  src/controller/command/create/AllDayRecurringEventCreator.java
  src/controller/command/create/AllDayRecurringUntilEventCreator.java
  src/controller/command/create/CreateEventCommand.java
  src/controller/command/create/EventCreator.java
  src/controller/command/create/RecurringEventCreator.java
  src/controller/command/create/RecurringUntilEventCreator.java
  src/controller/command/create/SingleEventCreator.java
  src/controller/command/edit/EditStrategy.java
  src/controller/command/edit/EditStrategyFactory.java
  src/controller/parser/CommandParser.java
  src/model/event/EventCreationStrategy.java
Labels: enhancement, A5_Feature, donedev

#29 Yash branch
  src/controller/command/CommandFactory.java
  src/controller/command/create/AbstractEventCreator.java
  src/controller/command/create/AllDayEventCreator.java
  src/controller/command/create/AllDayRecurringEventCreator.java
  src/controller/command/create/AllDayRecurringUntilEventCreator.java
  src/controller/command/create/CreateEventCommand.java
  src/controller/command/create/EventCreator.java
  src/controller/command/create/RecurringEventCreator.java
  src/controller/command/create/RecurringUntilEventCreator.java
  src/controller/command/create/SingleEventCreator.java
  src/controller/command/edit/EditStrategy.java
  src/controller/command/edit/EditStrategyFactory.java
  src/controller/parser/CommandParser.java
  src/model/event/EventCreationStrategy.java
Labels: wip, indev, newMod

#30 Feature edit strategy refactor
  src/controller/command/edit/AbstractEventEditor.java
  src/controller/command/edit/AllEventsEditor.java
  src/controller/command/edit/EditEventCommand.java
  src/controller/command/edit/EditStrategy.java
  src/controller/command/edit/EditStrategyFactory.java
  src/controller/command/edit/EventEditor.java
  src/controller/command/edit/SeriesFromDateEditor.java
  src/controller/command/edit/SingleEventEditor.java
  src/controller/parser/CommandParser.java
Labels: enhancement, A5_Feature, donedev, newMod

#32 whitespace refactoring
  src/controller/CalendarController.java
  src/controller/command/ICommand.java
  src/controller/command/calendar/CalendarCommandFactory.java
  src/controller/command/calendar/CalendarCommandHandler.java
  src/controller/command/copy/CopyEventCommand.java
  src/controller/command/copy/strategy/CopyStrategy.java
  src/controller/command/copy/strategy/CopyStrategyFactory.java
  src/controller/command/copy/strategy/DayEventsCopyStrategy.java
  src/controller/command/copy/strategy/RangeEventsCopyStrategy.java
  src/controller/command/copy/strategy/SingleEventCopyStrategy.java
  src/controller/command/create/CreateEventCommand.java
  src/controller/command/create/strategy/AbstractEventCreator.java
  src/controller/command/create/strategy/AllDayEventCreator.java
  src/controller/command/create/strategy/AllDayRecurringEventCreator.java
  src/controller/command/create/strategy/AllDayRecurringUntilEventCreator.java
  src/controller/command/create/strategy/EventCreator.java
  src/controller/command/create/strategy/RecurringEventCreator.java
  src/controller/command/edit/strategy/AbstractEventEditor.java
  src/controller/command/edit/strategy/AllEventsEditor.java
  src/controller/command/edit/strategy/EventEditor.java
  src/controller/command/edit/strategy/SeriesFromDateEditor.java
  src/controller/command/edit/strategy/SingleEventEditor.java
  src/controller/command/event/PrintEventsCommand.java
  src/controller/command/event/ShowStatusCommand.java
  src/controller/parser/CommandParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/calendar/ICalendar.java
  src/model/event/Event.java
  src/model/event/EventAction.java
  src/model/event/EventCreationStrategy.java
  src/model/factory/CalendarFactory.java
  src/resources/calcmd.txt
  src/resources/cmd10.txt
  src/resources/commands.txt
  src/test/java/CalendarCommandFactoryTest.java
  src/test/java/CalendarCommandHandlerTest.java
  src/test/java/CalendarControllerTest.java
  src/test/java/CalendarFactoryTest.java
  src/test/java/CalendarTest.java
Labels: enhancement

#33 Enhancement branch 1
  src/controller/command/CommandAdapter.java
  src/controller/command/create/strategy/AllDayRecurringEventCreator.java
  src/controller/command/create/strategy/AllDayRecurringUntilEventCreator.java
  src/controller/command/create/strategy/EventCreator.java
  src/controller/command/create/strategy/RecurringEventCreator.java
  src/controller/command/create/strategy/RecurringUntilEventCreator.java
  src/controller/command/create/strategy/SingleEventCreator.java
  src/controller/command/edit/strategy/AllEventsEditor.java
  src/controller/command/edit/strategy/SeriesFromDateEditor.java
  src/controller/command/edit/strategy/SingleEventEditor.java
  src/controller/command/event/CommandFactory.java
  src/controller/command/event/PrintEventsCommand.java
  src/controller/command/event/ShowStatusCommand.java
  src/test/java/AllDayEventCreatorTest.java
  src/test/java/AllDayRecurringEventCreatorTest.java
  src/test/java/AllDayRecurringUntilEventCreatorTest.java
  src/test/java/CalendarControllerTest.java
  src/test/java/RecurringEventCreatorTest.java
  src/test/java/RecurringUntilEventCreatorTest.java
  src/test/java/SingleEventCreatorTest.java
Labels: enhancement, testing

#35 Test case refactoring branch
  readme.md
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/command/calendar/CalendarCommandFactory.java
  src/controller/parser/CommandParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/calendar/ICalendar.java
  src/test/java/CalendarCommandFactoryTest.java
  src/test/java/CalendarControllerTest.java
  src/test/java/CalendarNameValidatorTest.java
  src/test/java/CommandParserTest.java
  src/test/java/CopyEventCommandTest.java
  src/utilities/CSVExporter.java
  src/utilities/CalendarNameValidator.java
  src/utilities/TimeZoneHandler.java
Labels: bug, A5_Feature

#36 csv exporter test cases updated to use streams and collections
  src/test/java/CSVExporterTest.java
Labels: enhancement, A5_Feature

#37 Test case refactoring branch
  src/model/calendar/CalendarRegistry.java
  src/model/calendar/EventFilter.java
  src/model/event/EventAction.java
  src/model/event/EventCreationStrategy.java
  src/test/java/CSVExporterTest.java
  src/test/java/EventActionTest.java
  src/test/java/EventFilterTest.java
Labels: enhancement, A5_Feature, testing

#38 Test case refactoring branch
  src/controller/CalendarController.java
  src/controller/command/calendar/CalendarCommandFactory.java
  src/controller/command/create/strategy/SingleEventCreator.java
  src/controller/parser/CommandParser.java
  src/test/java/CalendarCommandFactoryTest.java
  src/test/java/CalendarNameValidatorTest.java
  src/test/java/CommandParserTest.java
  src/test/java/CopyEventCommandTest.java
  src/test/java/EditEventCommandTest.java
  src/test/java/EventFilterTest.java
  src/test/java/RecurringUntilEventCreatorTest.java
  src/test/java/SingleEventCreatorTest.java
  src/utilities/CalendarNameValidator.java
Labels: A5_Feature, testing, newMod

#39 Enhancement branch 1
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/command/calendar/CalendarCommandFactory.java
  src/controller/command/create/strategy/SingleEventCreator.java
  src/controller/parser/CommandParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarRegistry.java
  src/model/calendar/EventFilter.java
  src/model/calendar/ICalendar.java
  src/model/event/EventAction.java
  src/model/event/EventCreationStrategy.java
  src/test/java/CSVExporterTest.java
  src/test/java/CalendarCommandFactoryTest.java
  src/test/java/CalendarControllerTest.java
  src/test/java/CalendarNameValidatorTest.java
  src/test/java/CommandParserTest.java
  src/test/java/CopyEventCommandTest.java
  src/test/java/EditEventCommandTest.java
  src/test/java/EventActionTest.java
  src/test/java/EventFilterTest.java
  src/test/java/RecurringUntilEventCreatorTest.java
  src/test/java/SingleEventCreatorTest.java
  src/utilities/CSVExporter.java
  src/utilities/CalendarNameValidator.java
  src/utilities/TimeZoneHandler.java
Labels: documentation, A5_Feature, donedev

#40 test enhancements
  src/family_events.csv
  src/resources/headlessCmd2.txt
  src/sports_events.csv
  src/test/java/CalendarCommandFactoryTest.java
  src/travel_events.csv
  src/university_events.csv
  src/work_events.csv
Labels: enhancement, A5_Feature, donedev

#41 styling fix 1
  .idea/artifacts/PDPAssignment5_jar.xml
  Assignment 5 (Part 2).pdf
  readme.md
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/command/calendar/CalendarCommandFactory.java
  src/controller/command/copy/strategy/DayEventsCopyStrategy.java
  src/controller/command/copy/strategy/RangeEventsCopyStrategy.java
  src/controller/command/copy/strategy/SingleEventCopyStrategy.java
  src/controller/command/create/strategy/AbstractEventCreator.java
  src/controller/command/create/strategy/EventCreator.java
  src/controller/command/create/strategy/RecurringUntilEventCreator.java
  src/controller/parser/CommandParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/calendar/EventFilter.java
  src/model/calendar/ICalendar.java
  src/model/event/Event.java
  src/model/event/RecurringEvent.java
  src/utilities/CSVExporter.java
  src/utilities/DateTimeUtil.java
Labels: styling

#42 utilities package refactoring adhereing to MVC now
  readme.md
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/command/calendar/CalendarCommandFactory.java
  src/controller/command/calendar/ErrorCommand.java
  src/controller/command/calendar/ExportCalendarCommand.java
  src/controller/command/calendar/ICalendarCommand.java
  src/controller/command/copy/CopyEventCommand.java
  src/controller/command/copy/strategy/CopyStrategyFactory.java
  src/controller/command/copy/strategy/DayEventsCopyStrategy.java
  src/controller/command/copy/strategy/RangeEventsCopyStrategy.java
  src/controller/command/copy/strategy/SingleEventCopyStrategy.java
  src/controller/input/CommandInputSource.java
  src/controller/input/ConsoleCommandInputSource.java
  src/controller/input/FileCommandInputSource.java
  src/io/CSVCalendarExporter.java
  src/io/CalendarExporter.java
  src/model/calendar/Calendar.java
  src/model/calendar/CalendarManager.java
  src/model/calendar/EventStorage.java
  src/model/core/datetime/DateTimeWrapper.java
  src/model/core/timezone/TimeZoneHandler.java
  src/model/core/timezone/TimezoneConverter.java
  src/model/core/updater/EventPropertyUpdater.java
  src/model/core/validation/CalendarNameValidator.java
  src/model/factory/CalendarFactory.java
  src/test/java/CSVCalendarExporterTest.java
  src/test/java/CSVExporterTest.java
  src/test/java/CalendarCommandFactoryTest.java
  src/test/java/CalendarControllerTest.java
  src/test/java/CalendarFactoryTest.java
  src/test/java/CalendarNameValidatorTest.java
  src/test/java/CalendarTest.java
  src/test/java/CopyEventCommandTest.java
  src/test/java/CreateEventCommandTest.java
  src/test/java/EditEventCommandTest.java
  src/test/java/EventActionTest.java
  src/test/java/EventFilterTest.java
  src/test/java/RecurringUntilEventCreatorTest.java
  src/test/java/SingleEventCreatorTest.java
Labels: enhancement

#47 Styling changes
  src/CalendarApp.java
  src/controller/CalendarController.java
  src/controller/command/copy/strategy/DayEventsCopyStrategy.java
  src/controller/command/copy/strategy/RangeEventsCopyStrategy.java
  src/controller/command/copy/strategy/SingleEventCopyStrategy.java
  src/controller/command/create/strategy/EventCreator.java
  src/controller/parser/CommandParser.java
  src/model/calendar/Calendar.java
  src/model/calendar/ICalendar.java
  src/model/event/EventAction.java
Labels: styling
